name: rss_generator
description: An RSS (Atom) generator
version: 1.0.0
homepage: https://github.com/g123k/dart_rss_generator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  xml: ^6.0.1
  intl: ^0.17.0
  date_time_format: ^2.0.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.1
