name: rss_generator
description: An RSS (Atom) generator
version: 1.0.0
homepage: https://github.com/g123k/dart_rss_generator

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  xml: ^6.5.0
  intl: ^0.19.0
  date_time_format: ^2.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
